name: Deploy Blog Pages

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # 将目标分支 checkout 到运行环境
      - uses: actions/setup-node@v4 # 安装 node@20
        with:
          node-version: '20'
      - run: npm install -g pnpm # 安装 PNPM
      - run: pnpm install --frozen-lockfile # 根据 lock 文件安装依赖

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run docs:build

      - name: Deploy to Nginx Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # 私钥id_rsa
          ALIYUN_SERVER_IP: ${{ secrets.ALIYUN_SERVER_IP }} # 云服务器IP地址
          ALIYUN_SERVER_PASSWORD: ${{ secrets.ALIYUN_SERVER_PASSWORD }} # 云服务器密码
          ALIYUN_SERVER_USER: ${{ secrets.ALIYUN_SERVER_USER }} # 云服务器用户名 默认为root
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }} # 云服务器部署目录 /home/blog/coffee-bean-blog/.vitepress/dist
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $ALIYUN_SERVER_IP >> ~/.ssh/known_hosts
          #scp -r ./.vuepress/dist/* $ALIYUN_SERVER_USER@$ALIYUN_SERVER_IP:$REMOTE_PATH
          sshpass -p $ALIYUN_SERVER_PASSWORD scp -r ./.vitepress/dist/* root@$ALIYUN_SERVER_IP:$REMOTE_PATH
